EURISTest/Controllers/CatalogController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using EURIS.Entities;
using EURISTest.Models;
using EURIS.Service;

namespace EURISTest.Controllers
{
    public class CatalogController : BaseController
    {
        private readonly ICatalogManager _service = new CatalogManager();

        //
        // GET: /Default1/

        public ActionResult Index()
        {
            List<Catalog> catalogs = new List<Catalog>();

            catalogs = _service.GetCatalogs();

            return View(catalogs);
        }

        //
        // GET: /Default1/Details/5

        public ActionResult Details(int id = 0)
        {
            Catalog catalog = _service.Read(id);

            if (catalog == null)
            {
                return HttpNotFound();
            }
            return View(catalog);
        }

        //
        // GET: /Default1/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Default1/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Catalog catalog)
        {
            if (_service.CodeUsedYet(catalog.Code)) {
                ModelState.AddModelError("Code", "Code is yet used.");
            }

            if (ModelState.IsValid)
            {
                ManageResult(_service.Create(catalog));
                return RedirectToAction("Index");
            }

            return View(catalog);
        }

        //
        // GET: /Default1/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Catalog catalog = _service.Read(id);

            if (catalog == null)
            {
                return HttpNotFound();
            }
            return View(catalog);
        }

        //
        // POST: /Default1/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Catalog catalog)
        {
            if (_service.CodeUsedYet(catalog.Code, catalog.Id))
            {
                ModelState.AddModelError("Code", "Code is yet used for an other catalog.");
            }

            if (ModelState.IsValid)
            {
                ManageResult(_service.Update(catalog));
                return RedirectToAction("Index");
            }
            return View(catalog);
        }

        //
        // GET: /Default1/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Catalog catalog = _service.Read(id);

            if (catalog == null)
            {
                return HttpNotFound();
            }

            return View(catalog);
        }

        //
        // POST: /Default1/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Catalog catalog = _service.Read(id);

            if (catalog == null)
            {
                return HttpNotFound();
            }

            ManageResult(_service.Delete(catalog));

            return RedirectToAction("Index");
        }

        public ActionResult Products(int id = 0)
        {
            Catalog catalog = _service.Read(id);

            if (catalog == null)
            {
                return HttpNotFound();
            }
            return View(catalog);
        }

        public ActionResult RemoveProduct(int idCatalog = 0, int idProduct = 0)
        {
            Catalog catalog = _service.Read(idCatalog);

            if (catalog == null)
            {
                return HttpNotFound();
            }

            ManageResult(_service.RemoveProduct(catalog, idProduct));

            return RedirectToAction("Products", new { @id = idCatalog });
        }

        public ActionResult AddProducts(int id = 0)
        {
            Catalog catalog = _service.Read(id);

            if (catalog == null)
            {
                return HttpNotFound();
            }

            AddProductModel pageModel = new AddProductModel();

            pageModel.Products = _service.GetProductNotCoupled(catalog);
            pageModel.IdCatalog = catalog.Id;

            return View(pageModel);
        }

        [HttpPost, ActionName("AddProducts")]
        public ActionResult AddProductsPost(AddProductModel inModel)
        {
            Catalog catalog = _service.Read(inModel.IdCatalog);
            if (catalog == null)
            {
                return HttpNotFound();
            }

            ManageResult(_service.AddProduct(catalog, inModel.SelectedProducts));

            return RedirectToAction("Products", new { id = inModel.IdCatalog });
        }
    }
}

EURISTest/Controllers/ProductController.cs
using System.Web.Mvc;
using EURIS.Entities;
using EURIS.Service;
using System.Collections.Generic;

namespace EURISTest.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductManager _service = new ProductManager();

        //
        // GET: /Product/

        public ActionResult Index()
        {
            List<Product> products = new List<Product>();

            products = _service.GetProducts();

            return View(products);
        }

        //
        // GET: /Product/Details/5

        public ActionResult Details(int id = 0)
        {
            Product product = _service.Read(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // GET: /Product/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Product/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            if (_service.CodeUsedYet(product.Code))
            {
                ModelState.AddModelError("Code", "Code is yet used.");
            }

            if (ModelState.IsValid)
            {
                ManageResult(_service.Create(product));
                return RedirectToAction("Index");
            }

            return View(product);
        }

        //
        // GET: /Product/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Product product = _service.Read(id);

            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // POST: /Product/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product)
        {
            if (_service.CodeUsedYet(product.Code, product.Id))
            {
                ModelState.AddModelError("Code", "Code is used for an other product.");
            }

            if (ModelState.IsValid)
            {
                ManageResult(_service.Update(product));
                return RedirectToAction("Index");
            }
            return View(product);
        }

        //
        // GET: /Product/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Product product = _service.Read(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // POST: /Product/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = _service.Read(id);

            if (product == null)
            {
                return HttpNotFound();
            }

            ManageResult(_service.Delete(product));

            return RedirectToAction("Index");
        }
    }
}

EURISTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesome/css/all.min.css")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("EURIS", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <nav class="navbar navbar-expand-md">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Product")">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Catalog")">Catalog</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            <h1 class="bd-title">@ViewBag.Title</h1>
            @if (TempData["Popup"] != null)
            {
                <div class="form-group">
                    <div class="@TempData["PopupType"]" role="alert">
                        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                        <strong><li class="fas @TempData["Icon"]"></li> @TempData["MessageStrong"]</strong> @TempData["Message"]
                    </div>
                </div>
            }
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <span class="text-muted"><li class="fas fa-copyright"></li> @DateTime.Now.Year - Gruppo EURIS</span>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>